package main

type Quote struct {
  Text  string
  Img   string
}

var DB = [...]Quote{
  {"Sauf que moi j'les baise moi les ménagères.", "menageres.jpeg"},
  {"Je suis l’homme le plus classe du monde, bande de cons.", "classe.jpeg"},
  {"Si tu veux m'parler, envoie-moi un... fax.", "fax.jpeg"},
  {"Je suis pas gentil, c’est pas vrai. Quand je m’énerve, je me mets dans des états dingues. Je suis méconnaissable.", "dingue.jpeg"},
  {"Sexe + histoire de cul = meurtre.", "sexe_maths.jpeg"},
  {"Est-ce que tu aimerais te bâfrer un chili con carne ?", "chili.jpeg"},
  {"Aime-moi tendre, aime-moi vrai.", "tendre.jpeg"},
  {"Je faisais l'amour avec lui depuis le samedi après-midi jusqu'au vendredi soir. À ce moment là c'était un bon compagnon.", "compagnon.jpeg"},
  {"Eh, la choucroute ! Si tu veux une saucisse…", "choucroute.jpeg"},
  {"En puissance intellectuelle, on va voir c'que tu vaux.", "puissance.jpeg"},
  {"Et c'est façile de traiter les gens de pédés. Tout ça parce que deux garçons vivent ensemble dans un ranch et portent des pantalons en cuir.", "pedes.jpeg"},
  {"Tu dépenses tout ton argent dans les habits et accessoires de mode mais tu es ridicule.", "ridicule.jpeg"},
  {"Bon ben lui il va m'prendre la tête.", "tete.jpeg"},
  {"Moi, j'veux être connu, tu sais pouquoi ? Pour niquer les gonzesses. Quand t'es célèbre tu niques plein de gonzesses.", "gonzesses.jpeg"},
  {"Classe, man ! Top of the pop.", "pop.jpeg"},
  {"Actuellement j'ai un léger problème de costume, je crois que mon tailleur se fout de ma gueule.", "costume.jpeg"},
  {"Je préfère partir plutôt que d’entendre ça plutôt que d’être sourd.", "sourd.jpeg"},
  {"Et ça chauffera pour ton cul.", "cul.jpeg"},
  {"Tu fais un amalgame entre la coquetterie et la classe.", "amalgame.jpeg"},
  {"Boah et puis merde, j’ai même plus envie de me laver !", "lave.jpeg"},
  {"Rassurez-moi. Vous seriez pas un peu en train d'me prendre pour un con des fois ?", "con.jpeg"},
  {"Moi ce qui me fait chier c’est les effets spéciaux minables. Je supporte plus.", "effetsspeciaux.jpeg"},
  {"Il était trop balourd, trop pataud. Il voulait pas m'lâcher la touffe.", "touffe.jpeg"},
  {"On va manger... des chips. T'entends ? Des chips. C'est tout c'que ça t'fait quand j'te dis qu'on va manger des chips ?", "chips.jpeg"},
  {"Vous voulez niquer avec mon ami et moi ?", "niquer.jpeg"},
  {"Elle s’est fait refaire les nichons, elle. Et je sais de quoi je parle.", "nichons.jpeg"},
  {"Tu n'es vraiment pas très sympa. Mais le train de tes injures roule sur le rail de mon indifférence.", "injures.jpeg"},
  {"J'suis limite nervous breakdown.", "breakdown.jpeg"},
  {"Ça sent le pipeau ton histoire. Le pipeau !", "pipeau.jpeg"},
  {"Mais j'suis pas super fort, j'suis mieux qu'ça même. J'suis surpuissant.", "surpuissant.jpeg"},
  {"Ok, puisque j'vois qu'on peut pas discuter, on va faire un duel.", "duel.jpeg"},
  {"J’en ai pour plus d’une barre de fringues sur moi.", "fringues.jpeg"},
  {"Ah ben là patron vous m’avez convaincu, c’est une bonne raison.", "convaincu.jpeg"},
  {"Oui, on en a chié pour trouver cette idée, on a été charrette.", "idee.jpeg"},
  {"Hé ben. J'ai connu un mec de droite, une fois. Il avait dix fois plus de classe.", "droite.jpeg"},
  {"Quand je serai célèbre, je me ferai des meufs ! Mmh je ferai des folies !", "meufs.jpeg"},
  {"Je pense que t'es un ouf toi. Un ouf malade.", "ouf.jpeg"},
  {"Putain, j'me suis mal démerdé. Pourtant, j'ai pas fait une concession.", "demerder.jpeg"},
  {"C'que j'arrête c'est les Pin's vieux. Ça m'fait plus marrer.", "pins.jpeg"},
  {"Au revoir messieurs dames. C'est ça la puissance intellectuelle. Bac+2, les enfants.", "bac.jpeg"},
  {"Si tu veux mon opinion, ça fait un peu… has been.", "hasbeen.jpeg"},
  {"Moi je préfèrerais avoir sa classe plutôt qu’avoir la mienne. Moi je suis un peu just.", "just.jpeg"},
  {"Alors une, je ne m’en souviens pas, deux je ne suis pas resté longtemps, et enfin cinq… il y a pas de cinq.", "cinq.jpeg"},
  {"Est-ce que vous voulez être ma femme ? Et après on boira un café.", "cafe.jpeg"},
  {"Ça va fuser, les potins, les ragots.", "fuser.jpeg"},
  {"Bon ça va, on vous fait pas chier là ? Non c'est sûr ? Je rêve.", "chier.jpeg"},
  {"Vous dites que j'aille me faire foutre ? OK j'y vais.", "foutre.jpeg"},
  {"Bababa baba baba. J'ai les bonbons qui collent au papier.", "bonbons.jpeg"},
  {"Oui je pourrais, mais d’abord faut sucer.", "sucer.jpeg"},
  {"Style le grand play-boy des fonds marins.", "playboy.jpeg"},
  {"On l'a retrouvé assassiné un jour. Il en est mort.", "assassine.jpeg"},
  {"Mon mari est absent. Vous voulez voir mes fesses ? Et ensuite j'vous roulerai une pelle.", "fesses.jpeg"},
  {"Alors que moi, pendant c'temps-là, j'me la suis donné grave.", "grave.jpeg"},
  {"Tu dois avoir le cul qui brille.", "brille.jpeg"},
}
